name: portfolio-api
services:
  api.stephlangley.me:
    # env_file: ".env"
    platform: linux/arm64
    image: ghcr.io/stephanielangley/portfolio/api:latest
    build:
      context: .
    container_name: api.stephlangley.me
    ports:
      - 80:8080
    environment:
      - STRAVACLIENTID
      - STRAVAATHLETEID
      - STRAVASECRET
      - STRAVAAUTHURL
      - CONNECTIONSTRINGS__DEFAULTCONNECTION

networks:
  default:
    name: main
    external: true
